### ISSUE TITLE
Log files don't display version names

### ISSUE THREAD

**Issue by caufieldjh** [Knowledge-Graph-Hub/automate-pheno-comparisons#46]
The log files produced during the build don't contain source version names as expected.
Example, from `HP_vs_HP_semsimian_phenio_20250403_log.yaml`:
```yaml
name: HP_vs_HP_semsimian_phenio_20250403
min_ancestor_information_content: 1.5
versions:
  hp:
  phenio:
```
